lines = 1
icon_size = 25

anchor_right = false
anchor_top = false
anchor_bottom = false

margin_top = 100

width = 650
height = 500

markup_extra = 'foreground="gray" font_size="smaller"'
markup_highlight = 'weight="bold" underline="low"'

exclude = [
  "qv4l2",
  "qvidcap",
]
